#!/bin/sh

# Attach frida objection onto Android application
# Usage: attach <app-name>

delimiter="================================================================"

#  -----------
# | Functions |
#  -----------

dependency_checks() {
	# Check if dependencies are installed

	if ! which uv 2>/dev/null 1>&2
	then
		printf "%s\n" "${delimiter}"
		printf "uv not installed\n"
		printf "%s\n" "${delimiter}"
		exit 1
	elif ! which adb 2>/dev/null 1>&2
	then
		printf "%s\n" "${delimiter}"
		printf "android-tools not installed.\n"
		printf "%s\n" "${delimiter}"
		exit 1
	elif [[ $(find . -maxdepth 1 -type f -name uv.lock) == "" ]]
	then
		printf "%s\n" "${delimiter}"
		printf "No uv.lock present for this project. Please initialize the project using uv init\n";
		printf "%s\n" "${delimiter}"
		exit 1
	elif [[ $(uv tool list | grep frida-tools) == "" ]]
	then
		printf "%s\n" "${delimiter}"
		printf "frida-tools not installed. Install it with uv tool install frida-tools\n"
		printf "%s\n" "${delimiter}"
		exit 1
	elif [[ $(uv tool list | grep objection) == "" ]]
	then
		printf "%s\n" "${delimiter}"
		printf "Frida objection not installed. Install it with uv tool install objection\n"
		printf "%s\n" "${delimiter}"
		exit 1
	fi
}

device_checks() {
	devices=$(adb devices | tail -2 | head -1)
	if [[ "${devices}" == "List of devices attached" ]]
	then
		printf "%s\n" "${delimiter}"
		printf "No device connected\n"
		printf "%s\n" "${delimiter}"
		exit 1
	fi
}

vanilla_with_hook() {
	# Running vanilla Frida with additional hooks
	local process_name="${1}"

	read -p "Please enter path to the hook JS file: " hook

	printf "%s\n" "${delimiter}"
	printf "Attaching Frida on process %d with hook %s\n" "${process_name}" "${hook}"
	printf "%s\n" "${delimiter}"

	uv run frida -U "${process_name}" -l "${hook}"
}

vanilla_without_hook() {
	# Running vanilla Frida without additional hooks
	local process_name="${1}"

	printf "%s\n" "${delimiter}"
	printf "Attaching Frida on process %s without additional hooks\n" "${process_name}"
	printf "%s\n" "${delimiter}"
	
	uv run frida -U "${process_name}"
}

attach_vanilla() {
	local process_name="${1}"
	while true
	do
		read -p "Do you want to attach a hook to the process (press Q to break)? [Y/N] " hook
		case "${hook}" in
			[Yy]* ) vanilla_with_hook "${process_name}" ;;
			[Nn]* ) vanilla_without_hook "${process_name}" ;;
			[Qq]* ) break ;;
			* ) printf "Choose [Y/N]\n"
		esac
	done
}

get_pid() {
	# Get process identifier of frida-server process
	local c=2
	local pid=$(adb shell ps -A | grep frida | cut -d " " -f ${c})

	while [[ "${pid}" == "" ]]
	do
		pid=$(adb shell ps -A | grep frida | cut -d " " -f ${c}) && ((c++))
	done

	echo "${pid}"
}

restart_server() {
	# Restart frida server on Android device (to prevent frida spawn errors)

	printf "%s\n" "${delimiter}"
	adb shell su -c 'killall frida-server'
	printf "Stopped current Frida server process\n"
	adb shell "su -c 'nohup /data/local/tmp/frida-server >/dev/null 2>&1 &'"
	pid=$(get_pid)
	printf "Started a new frida-server instance with a PID: %d\n" "${pid}"
	printf "Restart successful\n"
	printf "%s\n" "${delimiter}"
}

attach_process() {
	# Attach process to objection
	local pid="${1}"
	local process_name="${2}"

	while true
	do
		printf "Choose Frida toolkit version:\n\t1) Vanilla\n\t2) Objection\n\t3) Exit Script"
		read -p " " attach_choice
		case "${attach_choice}" in
			1* ) attach_vanilla "${process_name}" ;;
			2* ) uv run objection -g "${pid}" explore ;;
			3* ) restart_server && printf "Aborting script...\n" && exit 1 ;;
			* ) printf "Choose [1/2/3]\n"
		esac
	done
}

#  ---------------
# | Prerequisites |
#  ---------------

if [[ "${#}" -ne 1 ]] # ${#} - CMD argument count
then
	printf "1 argument needed, %d given. Usage: ./attach <app-name>\n" "${#}"
	exit 1
else
	name="${1}"
fi

dependency_checks

#  -----------
# | Main Flow |
#  -----------

process=$(uv run frida-ps -U | grep -i ${name})
process_count=$(echo "${process}" | wc -l)

if [[ "${process_count}" -ne 1 ]]
then
	printf "%d processes found. Please narrow your search into a single process\n" "${process_count}"
	exit 1
else
	pid=$(echo ${process} | cut -d " " -f 1)
	process_name=$(echo ${process} | cut -d " " -f 2)
	printf "Found process %s with pid %d\n" "${process_name}" "${pid}"
	while true
	do
		read -p "Do you want to attach the process to Frida? [Y/N] " choice
		case "${choice}" in
			[Yy]* ) attach_process "${pid}" "${process_name}" ;;
			[Nn]* ) restart_server && exit 1 ;;
			* ) printf "Choose [Y/N]\n"
		esac
	done
fi
