#!/bin/sh

# Automate CA certificate injection into Android System Trust Store
# Usage: inject_certificates <path-to-certificate>

delimiter="================================================================"

#  -----------
# | Functions |
#  -----------

dependency_checks() {
	if ! which openssl 2>/dev/null 1>&2
	then
		printf "%s\n" "${delimiter}"
		printf "[+] Openssl not installed.\n"
		printf "%s\n" "${delimiter}"
		exit 1
	elif ! which adb 2>/dev/null 1>&2
	then
		printf "%s\n" "${delimiter}"
		printf "[+] android-tools not installed.\n"
		printf "%s\n" "${delimiter}"
		exit 1
	else
		printf "%s\n" "${delimiter}"
		printf "[+] All dependencies installed\n"
		printf "%s\n" "${delimiter}"
	fi
}

argument_checks() {
	# Check the validity of provided command line arguments

	local name="${1}" # Name of a certificate file
	local ext="${2}" # Get extension of the full filename

	if ! [[ "${ext}" == "der" || "${ext}" == "pem" ]]
	then
		printf "%s\n" "${delimiter}"
		printf "[+] %s is not a valid certificate file\n" "${name}"
		printf "%s\n" "${delimiter}"
		exit 1
	fi
}

rename_pem_cert() {
	local cert="${1}"
	local cert_hash=$(openssl x509 -inform PEM -subject_hash_old -in ${cert} | head -1)
	cp "${cert}" "${cert_hash}.0"

	echo "${cert_hash}.0"
}

inject_certificates() {
	# Android security certificate injection script, adapted from httptoolkit
	local cert=${1}
	# Create a separate temp directory, to hold the current certificates
	# Without this, when we add the mount we can't read the current certs anymore.
	adb shell "su -c 'mkdir -p -m 700 /data/local/tmp/htk-ca-copy'"

	# Copy out the existing certificates
	adb shell "su -c 'cp /system/etc/security/cacerts/* /data/local/tmp/htk-ca-copy/'"

	# Create the in-memory mount on top of the system certs folder
	adb shell "su -c 'mount -t tmpfs tmpfs /system/etc/security/cacerts'"

	# Copy the existing certs back into the tmpfs mount, so we keep trusting them
	adb shell "su -c 'mv /data/local/tmp/htk-ca-copy/* /system/etc/security/cacerts/'"

	# Copy our new cert in, so we trust that too
	adb shell "su -c 'mv /sdcard/${cert} /system/etc/security/cacerts/'"

	# Update the perms & selinux context labels, so everything is as readable as before
	adb shell "su -c 'chown root:root /system/etc/security/cacerts/*'"
	adb shell "su -c 'chmod 644 /system/etc/security/cacerts/*'"
	adb shell "su -c 'chcon u:object_r:system_file:s0 /system/etc/security/cacerts/*'"

	# Delete the temp cert directory
	adb shell "su -c 'rm -r /data/local/tmp/htk-ca-copy'"
}

cleanup() {
	# Delete residual files
	local cert_name="${1}"

	if [[ "${cert_name}" != "" ]]
	then
		rm "${cert_name}"
	fi

	printf "%s\n" "${delimiter}"
	printf "[+] Deleted residual files\n"
	printf "%s\n" "${delimiter}"
}

#  ---------------
# | Prerequisites |
#  ---------------

if [ "${#}" -ne 1 ] # Exactly 1 command line argument should be provided as an input
then
	printf "%s\n" "${delimiter}"
	printf "[+] 1 argument needed, %d given. Usage: inject_certificates <path-to-certificate>\n" "${#}"
	printf "%s\n" "${delimiter}"
	exit 1
else
	name="${1}"
	ext="${1##*.}" # Get extension

	argument_checks "${name}" "${ext}" && dependency_checks

	# Check if Android device is connected
	devices=$(adb devices | tail -2 | head -1)
	if [[ "${devices}" == "List of devices attached" ]]
	then
		printf "%s\n" "${delimiter}"
		printf "[+] No device connected\n"
		printf "%s\n" "${delimiter}"
		exit 1
	fi
fi

#  -----------
# | Main Flow |
#  -----------

# Convert and rename certificates into an accepted format for Android System Trust Store
if [[ "${ext}" == "der" ]]
then
	# Certificate name after conversion
	out="${name%.*}.pem"
	openssl x509 -inform DER -in "${name}" -out "${out}"

	printf "%s\n" "${delimiter}"
	printf "[+] %s certificate converted to %s\n" "${name}" "${out}"
	printf "%s\n" "${delimiter}"

	cert_hash=$(rename_pem_cert "${out}")
elif [[ "${ext}" == "pem" ]]
then
	cert_hash=$(rename_pem_cert "${name}")
fi

printf "%s\n" "${delimiter}"
printf "[+] %s certificate renamed to %s\n" "${name}" "${cert_hash}"
printf "%s\n" "${delimiter}"

# Push certificate onto Android device
adb push "${cert_hash}" /sdcard/ 2>/dev/null

if [[ "${?}" -eq 0 ]] # ${?} - exit status of last executed command. 0 - successful execution.
then
	printf "%s\n" "${delimiter}"
	printf "[+] Pushed %s onto Android device\n" "${cert_hash}"
	printf "%s\n" "${delimiter}"

	inject_certificates "${cert_hash}"

	status_check=$(adb shell "su -c 'ls /system/etc/security/cacerts/${cert_hash}'")
	if [[ "${status_check}" == "" ]]
	then
		printf "%s\n" "${delimiter}"
		printf "[+] %s certificate injection has failed\n" "${cert_hash}"
		printf "%s\n" "${delimiter}"
	else
		printf "%s\n" "${delimiter}"
		printf "[+] %s certificate injection has been successful\n" "${cert_hash}"
		printf "%s\n" "${delimiter}"
	fi

	cleanup "${cert_hash}"
else
	printf "%s\n" "${delimiter}"
	printf "[+] Pushing %s onto Android device failed\n" "${cert_hash}"
	printf "%s\n" "${delimiter}"
fi
