#!/bin/sh

# Spawn Android process using Frida
# Usage: spawn_android <process-name>

delimiter="================================================================"

#  -----------
# | Functions |
#  -----------

argument_checks() {
	# Check whether an application with a given name exists on Android device
	local name="${1}"
    local package_list=$(adb shell pm list packages | grep -i ${name})
    local package_count=$(adb shell pm list packages | grep -i ${name} | wc -l)

	if [[ ${package_list} == "" ]]
	then
		printf "%s\n" "${delimiter}"
		printf "Package %s does not exist on this Android device\n" "${name}"
		printf "%s\n" "${delimiter}"
		exit 1
    elif [[ "${package_count}" -ne 1 ]]
    then
		printf "%s\n" "${delimiter}"
        printf "%d packages found. Please narrow search to a single package\n" "${package_count}"
        printf "Found packages:\n%s\n" "${package_list}"
		printf "%s\n" "${delimiter}"
        exit 1
	fi
}

dependency_checks() {
	# Check if dependencies are installed

	if ! which tee 2>/dev/null 1>&2
	then
		printf "%s\n" "${delimiter}"
		printf "tee not installed\n"
		printf "%s\n" "${delimiter}"
		exit 1
	elif ! which uv 2>/dev/null 1>&2
	then
		printf "%s\n" "${delimiter}"
		printf "uv not installed\n"
		printf "%s\n" "${delimiter}"
		exit 1
	elif ! which adb 2>/dev/null 1>&2
	then
		printf "%s\n" "${delimiter}"
		printf "android-tools not installed.\n"
		printf "%s\n" "${delimiter}"
		exit 1
	elif [[ $(find . -maxdepth 1 -type f -name uv.lock) == "" ]]
	then
		printf "%s\n" "${delimiter}"
		printf "No uv.lock present for this project. Please initialize the project using uv init\n";
		printf "%s\n" "${delimiter}"
		exit 1
	elif [[ $(uv tool list | grep frida-tools) == "" ]]
	then
		printf "%s\n" "${delimiter}"
		printf "frida-tools not installed. Install it with uv tool install frida-tools\n"
		printf "%s\n" "${delimiter}"
		exit 1
	fi
}

device_checks() {
	devices=$(adb devices | tail -2 | head -1)
	if [[ "${devices}" == "List of devices attached" ]]
	then
		printf "%s\n" "${delimiter}"
		printf "No device connected\n"
		printf "%s\n" "${delimiter}"
		exit 1
	fi
}

spawn_with_hook() {
	# Running vanilla Frida with additional hooks
	local process_name="${1}"

	read -p "Please enter path to the hook JS file: " hook

	printf "%s\n" "${delimiter}"
	printf "Spawning Frida on process %s with hook %s\n" "${process_name}" "${hook}"
	printf "%s\n" "${delimiter}"

	uv run frida -U -f "${process_name}" -l "${hook}" | tee -a frida.log
}

spawn_without_hook() {
	# Running vanilla Frida without additional hooks
	local process_name="${1}"

	printf "%s\n" "${delimiter}"
	printf "Spawning Frida on process %s without additional hooks\n" "${process_name}"
	printf "%s\n" "${delimiter}"

	uv run frida -U -f "${process_name}" | tee -a frida.log
}

get_pid() {
	# Get process identifier (PID) of frida-server
	local c=2
	local pid=$(adb shell ps -A | grep frida | cut -d " " -f ${c})

	while [[ "${pid}" == "" ]]
	do
		pid=$(adb shell ps -A | grep frida | cut -d " " -f ${c}) && ((c++))
	done

	echo "${pid}"
}

stop_process() {
	# Stop a given process
	local name="${1}"

	adb shell am force-stop ${name}
}

restart_server() {
	# Restart frida server on Android device (to prevent process respawn errors) and stop spawned process
	local full_name="${1}"

	if [[ $(ps -ef | grep attach_android | wc -l) -gt 1 ]]
	then
		printf "%s\n" "${delimiter}"
		printf "Attach-android process active, skipping frida-server restart\n"
		printf "%s\n" "${delimiter}"
	else
		printf "%s\n" "${delimiter}"

		if [[ $(adb shell ps -A | grep ${full_name} | wc -l) -eq 1 ]]
		then
			stop_process "${full_name}"
			printf "Stopped spawned %s process\n" "${full_name}"
		fi

		stop_process "frida-server"
		printf "Stopped current Frida server process\n"
		
		adb shell "su -c 'nohup /data/local/tmp/frida-server >/dev/null 2>&1 &'"
		pid=$(get_pid)
		printf "Started a new frida-server instance with a PID: %d\n" "${pid}"
		printf "Restart of frida-server successful\n"
		printf "%s\n" "${delimiter}"
	fi
}

#  ---------------
# | Prerequisites |
#  ---------------

if [[ "${#}" -ne 1 ]] # ${#} - CMD argument count
then
	printf "1 argument needed, %d given. Usage: spawn_android <process-name>\n" "${#}"
	exit 1
else
	name="${1}"
fi

argument_checks "${name}" && dependency_checks && device_checks

#  -----------
# | Main Flow |
#  -----------

while true
do
	full_name=$(adb shell pm list packages | grep -i ${name} | cut -d ":" -f 2)
	printf "Spawning process:\n\t%s\n" "${full_name}"
    read -p "Attach a hook to the spawned process (press Q to break)? [Y/N] " hook
    case "${hook}" in
        [Yy]* ) restart_server "${full_name}" && spawn_with_hook "${full_name}" ;;
        [Nn]* ) restart_server "${full_name}" && spawn_without_hook "${full_name}" ;;
        [Qq]* ) restart_server "${full_name}" && exit 1 ;;
        * ) printf "Choose [Y/N]\n"
    esac
done
